import { ROOM_IMAGES } from '@/content/images'

/** Hostel room inventory — single source of truth for the Stays page and the booking modal. */
export const ALL_ROOMS = [
  { id: 'mixed-dorm-6', name: 'Mixed dorm · 6 bed', category: 'dorm', kind: 'Dorm', badge: 'bg-teal text-white', popular: true, tagline: 'Social, affordable, and full of good people.', description: 'The social heart of the house. Pod beds with blackout curtains, a locker your backpack fits in, reading light and charging point. Bathrooms cleaned three times a day.', price: 499, originalPrice: 799, images: ROOM_IMAGES['mixed-dorm-6'], capacity: '1 per bed', bedType: 'Single pod', size: '40 sqft / pod', amenities: ['locker', 'curtain', 'light', 'charging', 'bathroom', 'wifi'], facts: ['1 per pod', '40 sqft / pod', 'Shared bath', 'Locker', 'Curtain', 'Daily housekeeping'], highlights: ['Pod-style beds', 'Privacy curtains', 'Daily housekeeping'], rating: 4.8, reviews: 234, locations: ['Darjeeling', 'Varanasi'], detailedDescription: ['Our Mixed Dorm is the heart of the Monkey House community.', 'Each bed has a personal locker, privacy curtain, and reading light.'], communityTags: ['Mostly solo travelers', 'Easy conversations', 'Social & vibrant'], houseRules: ['Quiet hours 11 PM – 7 AM', 'No food in dorms'], checkIn: '2:00 PM', checkOut: '11:00 AM', available: true },
  { id: 'female-dorm-6', name: 'Female dorm · 6 bed', category: 'dorm', kind: 'Women only', badge: 'bg-gold text-ink', tagline: 'A safe, welcoming space designed for women.', description: 'A quieter floor with keycard access, a vanity corner with proper lighting, and a community of women travellers who look out for each other.', price: 549, originalPrice: 849, images: ROOM_IMAGES['female-dorm-6'], capacity: '1 per bed', bedType: 'Single pod', size: '40 sqft / pod', amenities: ['locker', 'curtain', 'light', 'charging', 'bathroom', 'female', 'wifi'], facts: ['1 per pod', 'Keycard access', 'Vanity area', 'Blackout curtain', 'Locker', 'Women-only bath'], highlights: ['Women only', 'Keycard access', 'Vanity area'], rating: 4.9, reviews: 156, locations: ['Darjeeling', 'Varanasi'], detailedDescription: ['A dedicated space designed with women travelers in mind.', 'All pods feature personal lockers, blackout curtains, and reading lights.'], communityTags: ['Women-focused community', 'Safe & supportive'], houseRules: ['Female guests only', 'Quiet hours 11 PM – 7 AM'], checkIn: '2:00 PM', checkOut: '11:00 AM', available: true },
  { id: 'mixed-dorm-4', name: 'Mixed dorm · 4 bed', category: 'dorm', kind: 'Dorm', badge: 'bg-teal text-white', tagline: 'Intimate dorm vibes with more space per person.', description: 'Only four beds, so more space and less noise. Bigger lockers and an en-suite bathroom shared by your dorm alone. Great for a small group booking the whole room.', price: 649, originalPrice: 899, images: ROOM_IMAGES['mixed-dorm-4'], capacity: '1 per bed', bedType: 'Single pod', size: '50 sqft / pod', amenities: ['curtain', 'locker', 'light', 'charging', 'bathroom', 'wifi'], facts: ['1 per pod', '50 sqft / pod', 'En-suite bath', 'Large locker', 'Quieter'], highlights: ['Only 4 beds', 'En-suite bathroom', 'Large lockers'], rating: 4.9, reviews: 112, locations: ['Darjeeling', 'Varanasi'], detailedDescription: ['The cozier dorm option.', 'Includes an en-suite bathroom shared only between the 4 pod guests.'], communityTags: ['Close-knit group', 'Quieter vibe'], houseRules: ['Quiet hours 11 PM – 7 AM'], checkIn: '2:00 PM', checkOut: '11:00 AM', available: true },
  { id: 'private-double', name: 'Private double', category: 'private', kind: 'Private', badge: 'bg-ink text-white', tagline: 'Your own space, still part of the community.', description: 'A queen bed and a door that locks, with a private bathroom, AC and a desk. Full access to the kitchen, common rooms and every event. Privacy without the isolation.', price: 1499, originalPrice: 2199, images: ROOM_IMAGES['private-double'], capacity: '2 people', bedType: 'Queen bed', size: '180 sqft', amenities: ['bathroom', 'wifi', 'ac', 'charging', 'light'], facts: ['2 guests', '180 sqft', 'Queen bed', 'Private bath', 'AC', 'Work desk'], highlights: ['Private bathroom', 'Queen bed', 'Work desk'], rating: 4.9, reviews: 89, locations: ['Darjeeling', 'Varanasi'], detailedDescription: ['Your own cozy room with a comfortable queen bed.', 'Includes a private attached bathroom, AC, fast WiFi.'], communityTags: ['Best for couples', 'Work-friendly'], houseRules: ['Max 2 guests', 'Respect quiet hours'], checkIn: '2:00 PM', checkOut: '11:00 AM', available: true },
  { id: 'deluxe-suite', name: 'Deluxe suite', category: 'private', kind: 'Private', badge: 'bg-ink text-white', tagline: 'Premium comfort with the Monkey House spirit.', description: 'Our biggest room: king bed, private balcony facing Kanchenjunga, mini bar and coffee maker. For couples who want the view and the community. Darjeeling only.', price: 2499, originalPrice: 3499, images: ROOM_IMAGES['deluxe-suite'], capacity: '2 people', bedType: 'King bed', size: '280 sqft', amenities: ['bathroom', 'wifi', 'ac', 'charging', 'towel', 'kitchen'], facts: ['2 guests', '280 sqft', 'King bed', 'Balcony', 'Mini bar', 'Room service'], highlights: ['King bed', 'Private balcony', 'Mini bar & coffee'], rating: 5.0, reviews: 45, locations: ['Darjeeling'], detailedDescription: ['Our most spacious room with premium amenities.', 'Perfect for couples seeking comfort while still experiencing the community.'], communityTags: ['Luxury comfort', 'Balcony views'], houseRules: ['Max 2 guests', 'Early check-in available'], checkIn: '1:00 PM', checkOut: '12:00 PM', available: true },
]

export const getRoomsByDestination = (d) => ALL_ROOMS.filter((r) => !d || r.locations.includes(d))
export const HOSTEL_FROM_PRICE = Math.min(...ALL_ROOMS.map((r) => r.price))
